version: "0.1"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
    - 3306:3306
    restart: always
    privileged: true
    volumes:
    - /root/search/mysql/log:/var/log/mysql
    - /root/search/mysql/data:/var/lib/mysql
    - /root/search/mysql/conf:/etc/mysql
    - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  redis:
    image: redis
    container_name: redis
    ports:
    - 6379:6379
    restart: always
    privileged: true
    volumes:
    - /root/search/redis/conf/redis.conf:/etc/redis/redis.conf
    - /root/search/redis/data:/data
    - /etc/localtime:/etc/localtime:ro
    command: redis-server /etc/redis/redis.conf

  flask_search:
    image: flask_search
    container_name: flask_search
    ports:
    - 8080:8080
    restart: always
    privileged: true
    volumes:
    - /root/search/search-back/src1/config:/search/search/config
    - /root/search/search-back/src1/log:/search/log
    - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mysql
      - redis

  vue_search:
    image: vue_search
    container_name: vue_search
    ports:
    - 9001:80
    - 9002:9002
    restart: always
    privileged: true
    volumes:
    - /root/search/search-front/nginx/conf/conf.d:/etc/nginx/conf.d
    - /root/search/search-front/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    - /root/search/search-front/nginx/html:/usr/share/nginx/html
    - /root/search/search-front/nginx/log:/var/log/nginx
    - /etc/localtime:/etc/localtime:ro
    depends_on:
      - flask_search
